### ISSUE TITLE
add simple implementation of isOnScreen in commons

### ISSUE THREAD

**Issue by ryndel** [commons/common.js#23]
See the following resource for several examples of an isOnScreen function. 
Suggest we could add the most basic version in commons.
http://upshots.org/javascript/jquery-test-if-element-is-in-viewport-visible-on-screen#h-o

**Comment by tracend** [comment]
The solution relies in jQuery methods and although it can be re-written with VanillaJS it may be more sensible to just be treated as a code component.

**Comment by tracend** [comment]
Included the most minimal solution under the name ```c.visible```
